import type { GameCompanionConfig } from '../playground/gameCompanionTypes';
import { serializeGameConfigForAgent } from '../playground/gameCompanionTypes';

let gameAfkTimer: ReturnType<typeof setTimeout> | null = null;
let gameVisionTimer: ReturnType<typeof setInterval> | null = null;
let sessionLimitTimer: ReturnType<typeof setTimeout> | null = null;
let sessionStartMs = 0;

function jitterMs(baseSec: number, jitterSec: number): number {
  const delta = (Math.random() * 2 - 1) * jitterSec;
  return Math.max(30, baseSec + delta) * 1000;
}

function describeAfkAction(action: string, config: GameCompanionConfig): string {
  switch (action) {
    case 'move_wasd':
      return 'Press brief WASD movement keys to prevent idle kick';
    case 'jump':
      return 'Press space/jump key';
    case 'interact':
      return 'Press interact key (E/F)';
    case 'rotate_camera':
      return 'Small mouse movement to simulate activity';
    case 'press_random_key':
      return 'Press a safe random key from bindings';
    case 'click_center':
      return 'Left-click screen center';
    case 'scroll_wheel':
      return 'Small scroll wheel movement';
    case 'custom_macro':
      return `Run custom macro: ${config.customMacro}`;
    default:
      return action;
  }
}

export function buildGameplayMdContent(config: GameCompanionConfig): string {
  const title = config.gameTitle || 'Game';
  return `# ${title} — Gameplay Guide

> Auto-generated by Ocean.studio Active Bot. Updated as the bot learns your game.

## Configuration
\`\`\`
${serializeGameConfigForAgent(config)}
\`\`\`

## Overview
This file teaches the Active Bot how to interact with **${title}**.

## Process & Window
- Process: \`${config.processName || 'auto-detect'}\`
- Window title: \`${config.windowTitle || 'auto-detect'}\`
${config.launcherPath ? `- Launcher: \`${config.launcherPath}\`` : ''}
${config.androidPackageName ? `- Android package: \`${config.androidPackageName}\`` : ''}

## Controls & Key Bindings
| Action | Keys |
|--------|------|
${config.keyBindings.map((b) => `| ${b.action} | \`${b.keys}\` |`).join('\n')}

## Anti-AFK Strategy
${config.antiAfkEnabled
    ? `- Interval: every **${config.antiAfkIntervalSec}s** (±${config.antiAfkJitterSec}s jitter)
- Actions: ${config.antiAfkActions.map((a) => describeAfkAction(a, config)).join('; ')}`
    : '- Anti-AFK disabled'}

## Screen Regions
${config.screenRegions.map((r) => `- **${r.name}**: x=${r.x}, y=${r.y}, ${r.width}×${r.height}`).join('\n')}

## Vision
${config.visionEnabled
    ? `- Provider: ${config.visionProvider}, screenshot every ${config.screenshotIntervalSec}s`
    : '- Vision disabled — keyboard/mouse only'}

## Safety
- Pause on user input: ${config.pauseOnUserInput}
- Max session: ${config.maxSessionHours} hours
- Emergency stop: **${config.emergencyStopKey}**
- Safe zone only: ${config.safeZoneOnly}

## Strategies
- _Bot will document optimal interaction sequences here_

## Session Log
- Started: ${new Date().toISOString()}

${config.notes.trim() ? `## User Notes\n${config.notes.trim()}\n` : ''}
---
*Say "stop" or press ${config.emergencyStopKey} to end the Active Bot session.*
`;
}

export function buildGameAfkPrompt(config: GameCompanionConfig): string {
  const actions = config.antiAfkActions
    .map((a) => describeAfkAction(a, config))
    .join('; ');
  return `[Game Anti-AFK] Game: ${config.gameTitle || 'unknown'}. ` +
    `Input: ${config.inputMethod}, profile: ${config.controlProfile}. ` +
    `Execute: ${actions}. ` +
    `${config.focusBeforeAction ? 'Focus game window first. ' : ''}` +
    `${config.bringWindowToFront ? 'Bring window to front. ' : ''}` +
    `${config.safeZoneOnly ? 'Stay within defined screen regions. ' : ''}` +
    `Bindings: ${config.keyBindings.map((b) => `${b.action}=${b.keys}`).join(', ')}.`;
}

export function buildGameVisionPrompt(config: GameCompanionConfig): string {
  return `[Game Vision] Capture screen of ${config.gameTitle || 'game'}, analyze UI state, ` +
    `update gameplay.md with new controls/strategies. Provider: ${config.visionProvider}. ` +
    `Regions: ${config.screenRegions.map((r) => r.name).join(', ')}.`;
}

export function startGameCompanionTimers(
  config: GameCompanionConfig,
  onAfk: (prompt: string) => void,
  onVision: (prompt: string) => void,
  onSessionLimit: () => void,
): void {
  stopGameCompanionTimers();
  if (!config.enabled) return;

  sessionStartMs = Date.now();

  if (config.antiAfkEnabled && config.antiAfkActions.length > 0) {
    const scheduleAfk = () => {
      onAfk(buildGameAfkPrompt(config));
      gameAfkTimer = setTimeout(scheduleAfk, jitterMs(config.antiAfkIntervalSec, config.antiAfkJitterSec));
    };
    gameAfkTimer = setTimeout(scheduleAfk, jitterMs(config.antiAfkIntervalSec, config.antiAfkJitterSec));
  }

  if (config.visionEnabled) {
    gameVisionTimer = setInterval(() => {
      onVision(buildGameVisionPrompt(config));
    }, config.screenshotIntervalSec * 1000);
  }

  if (config.maxSessionHours > 0) {
    const limitMs = config.maxSessionHours * 60 * 60 * 1000;
    sessionLimitTimer = setTimeout(() => {
      if (Date.now() - sessionStartMs >= limitMs) onSessionLimit();
    }, limitMs);
  }
}

export function stopGameCompanionTimers(): void {
  if (gameAfkTimer) {
    clearTimeout(gameAfkTimer);
    gameAfkTimer = null;
  }
  if (gameVisionTimer) {
    clearInterval(gameVisionTimer);
    gameVisionTimer = null;
  }
  if (sessionLimitTimer) {
    clearTimeout(sessionLimitTimer);
    sessionLimitTimer = null;
  }
}
