import type { PlaygroundPlatform, PlaygroundToolCategory } from './types';

export type ThreeDMode = 'text-to-3d' | 'image-to-3d' | '2d-to-3d';

export interface ThreeDSource {
  id: string;
  name: string;
  description: string;
  mode: ThreeDMode | 'all';
  platforms: PlaygroundPlatform[];
  kind: 'opensource' | 'cloud' | 'mcp' | 'plugin';
  freeTier: boolean;
  gpuRequired?: boolean;
  envRequirements?: string;
  installGuide?: string;
  outputFormats: string[];
  icon: string;
}

/** Open-source / local models for Electron EXE — runs on user GPU */
export const ELECTRON_3D_SOURCES: ThreeDSource[] = [
  {
    id: 'triposr',
    name: 'TripoSR',
    description: 'Fast single-image to 3D mesh — MIT license, runs locally on GPU',
    mode: 'image-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, CUDA 11.8+, torch, triposr',
    installGuide: 'pip install triposr && ocean plugin install triposr-3d',
    outputFormats: ['glb', 'obj', 'ply'],
    icon: '⚡',
  },
  {
    id: 'instantmesh',
    name: 'InstantMesh',
    description: 'Tencent open-source image-to-3D with high-quality geometry',
    mode: 'image-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, CUDA 12+, instantmesh repo',
    outputFormats: ['glb', 'obj'],
    icon: '🧊',
  },
  {
    id: 'zero123plus',
    name: 'Zero123++',
    description: 'Multi-view diffusion for consistent 3D from single image',
    mode: '2d-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, diffusers, zero123++ weights',
    outputFormats: ['glb', 'nerf'],
    icon: '🔄',
  },
  {
    id: 'shap-e',
    name: 'OpenAI Shap-E',
    description: 'Text and image to 3D — open weights, local inference',
    mode: 'all',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, pip install shap-e',
    outputFormats: ['ply', 'obj'],
    icon: '🎨',
  },
  {
    id: 'point-e',
    name: 'OpenAI Point-E',
    description: 'Text to point cloud — lightweight local 3D generation',
    mode: 'text-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: false,
    envRequirements: 'PYTHON=3.10+, pip install point-e',
    outputFormats: ['ply'],
    icon: '✨',
  },
  {
    id: 'openlrm',
    name: 'OpenLRM',
    description: 'Large Reconstruction Model — single image to 3D',
    mode: 'image-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, CUDA, openlrm weights',
    outputFormats: ['glb', 'mesh'],
    icon: '🏗️',
  },
  {
    id: 'wonder3d',
    name: 'Wonder3D',
    description: 'Cross-domain diffusion for high-fidelity 3D from image',
    mode: '2d-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, CUDA 11.8+, wonder3d',
    outputFormats: ['glb', 'obj', 'texture'],
    icon: '🌟',
  },
  {
    id: 'crm',
    name: 'CRM (Conv Recon)',
    description: 'Convolutional reconstruction model for image-to-3D',
    mode: 'image-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.10+, CRM model weights',
    outputFormats: ['glb'],
    icon: '📐',
  },
  {
    id: 'trellis',
    name: 'TRELLIS',
    description: 'Microsoft open large 3D asset generation model',
    mode: 'text-to-3d',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: true,
    envRequirements: 'PYTHON=3.11+, CUDA 12+, trellis-3d',
    outputFormats: ['glb', 'usd'],
    icon: '🌲',
  },
  {
    id: 'blender-local',
    name: 'Blender Headless',
    description: 'Local Blender bpy pipeline for mesh refinement and export',
    mode: 'all',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    gpuRequired: false,
    envRequirements: 'BLENDER_PATH=/usr/bin/blender, PYTHON=3.10+',
    outputFormats: ['blend', 'glb', 'fbx', 'obj'],
    icon: '🎨',
  },
  {
    id: 'meshlab-cli',
    name: 'MeshLab CLI',
    description: 'Open-source mesh processing, decimation, and repair',
    mode: 'all',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    envRequirements: 'MESHLAB_SERVER=meshlabserver',
    outputFormats: ['ply', 'obj', 'stl'],
    icon: '🔧',
  },
  {
    id: 'open3d',
    name: 'Open3D',
    description: 'Point cloud and mesh processing library',
    mode: 'all',
    platforms: ['electron'],
    kind: 'opensource',
    freeTier: true,
    envRequirements: 'pip install open3d',
    outputFormats: ['ply', 'pcd', 'obj'],
    icon: '📊',
  },
];

/** Cloud APIs for Android APK — heavy GPU work offloaded, free tiers */
export const ANDROID_CLOUD_3D_SOURCES: ThreeDSource[] = [
  {
    id: 'meshy-cloud',
    name: 'Meshy AI',
    description: 'Text/image to 3D — free tier: 200 credits/month',
    mode: 'all',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'MESHY_API_KEY=msy_...',
    installGuide: 'Providers → Meshy or MCP meshy-3d',
    outputFormats: ['glb', 'fbx', 'obj', 'usdz'],
    icon: '🔷',
  },
  {
    id: 'tripo-cloud',
    name: 'Tripo AI',
    description: 'High-quality text-to-3D — free starter credits',
    mode: 'text-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'TRIPO_API_KEY=...',
    outputFormats: ['glb', 'fbx'],
    icon: '🏔️',
  },
  {
    id: 'luma-genie',
    name: 'Luma AI Genie',
    description: 'Text to 3D scenes — free tier available',
    mode: 'text-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'LUMA_API_KEY=...',
    outputFormats: ['glb', 'usdz'],
    icon: '✨',
  },
  {
    id: 'replicate-3d',
    name: 'Replicate 3D Models',
    description: 'TripoSR, InstantMesh, Shap-E on cloud GPU — pay per run, free credits',
    mode: 'all',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'REPLICATE_API_TOKEN=r8_...',
    outputFormats: ['glb', 'obj'],
    icon: '🔄',
  },
  {
    id: 'fal-3d',
    name: 'Fal.ai 3D',
    description: 'Fast cloud inference for Trellis, TripoSR — free tier',
    mode: 'all',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'FAL_KEY=...',
    outputFormats: ['glb'],
    icon: '⚡',
  },
  {
    id: 'huggingface-3d',
    name: 'HuggingFace Inference',
    description: 'Serverless Shap-E, Point-E, InstantMesh — free tier limits',
    mode: 'all',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'HF_TOKEN=hf_...',
    outputFormats: ['ply', 'glb'],
    icon: '🤗',
  },
  {
    id: 'csm-ai',
    name: 'CSM (Common Sense Machines)',
    description: 'Image to 3D mesh — free trial credits',
    mode: 'image-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'CSM_API_KEY=...',
    outputFormats: ['glb', 'fbx'],
    icon: '🧠',
  },
  {
    id: 'masterpiecex',
    name: 'Masterpiece X',
    description: 'Text to 3D game-ready assets — free tier',
    mode: 'text-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'MASTERPIECEX_API_KEY=...',
    outputFormats: ['glb', 'fbx'],
    icon: '🎮',
  },
  {
    id: 'spline-cloud',
    name: 'Spline AI',
    description: 'Text to 3D interactive scenes — free plan',
    mode: 'text-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'mcp',
    freeTier: true,
    envRequirements: 'SPLINE_API_KEY=...',
    outputFormats: ['spline', 'glb'],
    icon: '🎯',
  },
  {
    id: 'kaedim',
    name: 'Kaedim',
    description: '2D concept art to 3D model — trial credits',
    mode: '2d-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'KAEDIM_API_KEY=...',
    outputFormats: ['fbx', 'obj'],
    icon: '🖼️',
  },
  {
    id: 'rodin',
    name: 'Rodin (Hyper3D)',
    description: 'Text/image to detailed 3D — free generations',
    mode: 'all',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'HYPER3D_API_KEY=...',
    outputFormats: ['glb', 'usdz'],
    icon: '🗿',
  },
  {
    id: 'stability-3d',
    name: 'Stability AI 3D',
    description: 'Stable Fast 3D — cloud API with free credits',
    mode: 'image-to-3d',
    platforms: ['cloud', 'android'],
    kind: 'cloud',
    freeTier: true,
    envRequirements: 'STABILITY_API_KEY=sk-...',
    outputFormats: ['glb', 'obj'],
    icon: '🌀',
  },
];

export function get3DSourcesForPlatform(platform: 'electron' | 'android' | 'web'): ThreeDSource[] {
  if (platform === 'electron') {
    return [...ELECTRON_3D_SOURCES, ...ANDROID_CLOUD_3D_SOURCES.filter((s) => s.freeTier)];
  }
  if (platform === 'android') {
    return ANDROID_CLOUD_3D_SOURCES;
  }
  return ANDROID_CLOUD_3D_SOURCES.filter((s) => s.freeTier);
}

export const THREE_D_FEATURE_CATEGORIES: PlaygroundToolCategory[] = ['media-3d'];
