import type { OceanPluginManifest } from '../types';

/** Ocean.studio curated official marketplace */
export const OFFICIAL_PLUGINS: OceanPluginManifest[] = [
  {
    id: 'ocean.filesystem-mcp',
    name: 'Filesystem MCP',
    version: '1.0.0',
    description: 'Read and write files in your workspace via MCP protocol',
    author: 'Ocean.studio',
    platforms: ['electron', 'web'],
    type: 'mcp',
    tags: ['mcp', 'filesystem', 'official'],
    mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem'] },
    tools: [
      { name: 'read_file', description: 'Read file contents' },
      { name: 'write_file', description: 'Write file contents' },
      { name: 'list_directory', description: 'List directory contents' },
    ],
    source: 'official',
    verified: true,
    downloads: 12500,
    rating: 4.9,
  },
  {
    id: 'ocean.github-mcp',
    name: 'GitHub MCP',
    version: '1.0.0',
    description: 'GitHub repos, issues, PRs — same as Cursor and Claude Code',
    author: 'Ocean.studio',
    platforms: ['electron', 'web'],
    type: 'mcp',
    tags: ['mcp', 'github', 'official'],
    mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' } },
    configSchema: { GITHUB_PERSONAL_ACCESS_TOKEN: { type: 'string', description: 'GitHub PAT', default: '' } },
    source: 'official',
    verified: true,
    downloads: 9800,
    rating: 4.8,
  },
  {
    id: 'ocean.brave-search',
    name: 'Brave Search MCP',
    version: '1.0.0',
    description: 'Web search for the agent — used by Cursor and Codex',
    author: 'Ocean.studio',
    platforms: ['electron', 'web'],
    type: 'mcp',
    tags: ['mcp', 'search', 'official'],
    mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-brave-search'], env: { BRAVE_API_KEY: '' } },
    configSchema: { BRAVE_API_KEY: { type: 'string', description: 'Brave Search API key' } },
    source: 'official',
    verified: true,
    downloads: 7200,
    rating: 4.7,
  },
  {
    id: 'ocean.postgres-mcp',
    name: 'PostgreSQL MCP',
    version: '1.0.0',
    description: 'Query PostgreSQL databases from the agent',
    author: 'Ocean.studio',
    platforms: ['electron'],
    type: 'mcp',
    tags: ['mcp', 'database', 'official', 'desktop'],
    mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres'] },
    configSchema: { POSTGRES_CONNECTION_STRING: { type: 'string', description: 'PostgreSQL connection string' } },
    source: 'official',
    verified: true,
    downloads: 4100,
    rating: 4.6,
  },
  {
    id: 'ocean.python-runner',
    name: 'Python Runner',
    version: '1.0.0',
    description: 'Execute Python scripts and manage venvs on desktop',
    author: 'Ocean.studio',
    platforms: ['electron'],
    type: 'tool',
    tags: ['python', 'desktop', 'official'],
    electron: { python: 'agent/plugin_runner.py', entry: 'run' },
    tools: [{ name: 'run_python', description: 'Execute Python code in workspace' }],
    source: 'official',
    verified: true,
    downloads: 6300,
    rating: 4.8,
  },
  {
    id: 'ocean.firecrawl-web',
    name: 'Firecrawl Web Scraper',
    version: '1.0.0',
    description: 'Scrape and crawl websites from the web version',
    author: 'Ocean.studio',
    platforms: ['web'],
    type: 'mcp',
    tags: ['web', 'scrape', 'official'],
    mcp: { transport: 'sse', url: 'https://mcp.firecrawl.dev/sse' },
    configSchema: { FIRECRAWL_API_KEY: { type: 'string', description: 'Firecrawl API key' } },
    source: 'official',
    verified: true,
    downloads: 5500,
    rating: 4.7,
  },
  {
    id: 'ocean.termux-pkg',
    name: 'Termux Package Manager',
    version: '1.0.0',
    description: 'Full apt/pkg on Android — git, python, node, curl, proot',
    author: 'Ocean.studio',
    platforms: ['mobile'],
    type: 'connector',
    tags: ['mobile', 'termux', 'pkg', 'official'],
    mobile: { pkg: 'core', bootstrap: true },
    tools: [
      { name: 'pkg_install', description: 'Install packages via pkg/apt' },
      { name: 'proot_shell', description: 'Launch proot Linux environment' },
    ],
    source: 'official',
    verified: true,
    downloads: 8900,
    rating: 4.9,
  },
  {
    id: 'ocean.mobile-git',
    name: 'Mobile Git Tools',
    version: '1.0.0',
    description: 'Git clone, push, pull on Android native terminal',
    author: 'Ocean.studio',
    platforms: ['mobile'],
    type: 'tool',
    tags: ['mobile', 'git', 'official'],
    mobile: { pkg: 'git' },
    tools: [{ name: 'git_clone', description: 'Clone a repository' }],
    source: 'official',
    verified: true,
    downloads: 5200,
    rating: 4.6,
  },
  {
    id: 'ocean.slack-webhook',
    name: 'Slack Webhook',
    version: '1.0.0',
    description: 'Send agent notifications to Slack',
    author: 'Ocean.studio',
    platforms: ['electron', 'web', 'mobile'],
    type: 'webhook',
    tags: ['webhook', 'slack', 'official'],
    configSchema: { webhookUrl: { type: 'string', description: 'Slack webhook URL' } },
    source: 'official',
    verified: true,
    downloads: 3100,
    rating: 4.5,
  },
  // ── 21 more working plugins ──
  { id: 'ocean.memory-mcp', name: 'Memory MCP', version: '1.0.0', description: 'Persistent knowledge graph', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'memory'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'] }, tools: [{ name: 'store', description: 'Store knowledge' }], source: 'official', verified: true, downloads: 5200, rating: 4.7 },
  { id: 'ocean.sequential-thinking', name: 'Sequential Thinking', version: '1.0.0', description: 'Structured reasoning chains', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'ai'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] }, source: 'official', verified: true, downloads: 4800, rating: 4.8 },
  { id: 'ocean.puppeteer', name: 'Puppeteer Browser', version: '1.0.0', description: 'Browser automation', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'browser'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] }, source: 'official', verified: true, downloads: 3900, rating: 4.6 },
  { id: 'ocean.sqlite-mcp', name: 'SQLite MCP', version: '1.0.0', description: 'Local SQLite queries', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'database'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sqlite'] }, configSchema: { SQLITE_DB_PATH: { type: 'string', description: 'DB path' } }, source: 'official', verified: true, downloads: 3600, rating: 4.6 },
  { id: 'ocean.redis-mcp', name: 'Redis MCP', version: '1.0.0', description: 'Redis operations', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'database'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-redis'] }, source: 'official', verified: true, downloads: 2800, rating: 4.5 },
  { id: 'ocean.gitlab-mcp', name: 'GitLab MCP', version: '1.0.0', description: 'GitLab MRs and CI', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'gitlab'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-gitlab'] }, configSchema: { GITLAB_PERSONAL_ACCESS_TOKEN: { type: 'string', description: 'GitLab token' } }, source: 'official', verified: true, downloads: 3200, rating: 4.6 },
  { id: 'ocean.slack-mcp', name: 'Slack MCP', version: '1.0.0', description: 'Slack messaging', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'slack'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-slack'] }, configSchema: { SLACK_BOT_TOKEN: { type: 'string', description: 'Bot token' } }, source: 'official', verified: true, downloads: 4100, rating: 4.7 },
  { id: 'ocean.sentry-mcp', name: 'Sentry MCP', version: '1.0.0', description: 'Error tracking', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'devops'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sentry'] }, source: 'official', verified: true, downloads: 2400, rating: 4.5 },
  { id: 'ocean.fetch-mcp', name: 'Fetch MCP', version: '1.0.0', description: 'HTTP fetch tool', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'web'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-fetch'] }, source: 'official', verified: true, downloads: 3700, rating: 4.6 },
  { id: 'ocean.google-maps', name: 'Google Maps MCP', version: '1.0.0', description: 'Geocoding and places', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'maps'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-google-maps'] }, configSchema: { GOOGLE_MAPS_API_KEY: { type: 'string', description: 'API key' } }, source: 'official', verified: true, downloads: 2900, rating: 4.5 },
  { id: 'ocean.playwright', name: 'Playwright MCP', version: '1.0.0', description: 'Cross-browser testing', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'testing'], mcp: { command: 'npx', args: ['-y', '@playwright/mcp'] }, source: 'official', verified: true, downloads: 3400, rating: 4.7 },
  { id: 'ocean.e2b', name: 'E2B Sandbox', version: '1.0.0', description: 'Code execution sandbox', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['mcp', 'sandbox'], mcp: { command: 'npx', args: ['-y', '@e2b/mcp-server'] }, configSchema: { E2B_API_KEY: { type: 'string', description: 'E2B key' } }, source: 'official', verified: true, downloads: 2600, rating: 4.6 },
  { id: 'ocean.deepwiki-web', name: 'DeepWiki', version: '1.0.0', description: 'GitHub repo docs via SSE', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'web', 'sse'], mcp: { transport: 'sse', url: 'https://mcp.deepwiki.com/sse' }, source: 'official', verified: true, downloads: 4500, rating: 4.8 },
  { id: 'ocean.cloudflare-web', name: 'Cloudflare Docs', version: '1.0.0', description: 'Cloudflare documentation', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'cloudflare'], mcp: { transport: 'sse', url: 'https://docs.mcp.cloudflare.com/sse' }, source: 'official', verified: true, downloads: 3800, rating: 4.7 },
  { id: 'ocean.supabase-web', name: 'Supabase MCP', version: '1.0.0', description: 'Supabase database & auth', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'supabase'], mcp: { transport: 'sse', url: 'https://mcp.supabase.com/sse' }, configSchema: { SUPABASE_ACCESS_TOKEN: { type: 'string', description: 'Access token' } }, source: 'official', verified: true, downloads: 4200, rating: 4.8 },
  { id: 'ocean.linear-web', name: 'Linear MCP', version: '1.0.0', description: 'Issue tracking', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'linear'], mcp: { transport: 'sse', url: 'https://mcp.linear.app/sse' }, configSchema: { LINEAR_API_KEY: { type: 'string', description: 'API key' } }, source: 'official', verified: true, downloads: 3100, rating: 4.6 },
  { id: 'ocean.vercel-web', name: 'Vercel MCP', version: '1.0.0', description: 'Deployments', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'vercel'], mcp: { transport: 'sse', url: 'https://mcp.vercel.com/sse' }, configSchema: { VERCEL_TOKEN: { type: 'string', description: 'Token' } }, source: 'official', verified: true, downloads: 3500, rating: 4.7 },
  { id: 'ocean.perplexity-web', name: 'Perplexity Search', version: '1.0.0', description: 'AI web search', author: 'Ocean.studio', platforms: ['web', 'electron', 'mobile'], type: 'mcp', tags: ['mcp', 'search'], mcp: { transport: 'sse', url: 'https://mcp.perplexity.ai/sse' }, configSchema: { PERPLEXITY_API_KEY: { type: 'string', description: 'API key' } }, source: 'official', verified: true, downloads: 4000, rating: 4.7 },
  { id: 'ocean.git-agent', name: 'Git Workflow', version: '1.0.0', description: 'Clone, commit, push via terminal + GitHub OAuth', author: 'Ocean.studio', platforms: ['electron'], type: 'tool', tags: ['git', 'github'], tools: [{ name: 'git_clone', description: 'Clone repo' }, { name: 'git_push', description: 'Push commits' }], source: 'official', verified: true, downloads: 6700, rating: 4.9 },
  { id: 'ocean.docker-tool', name: 'Docker Manager', version: '1.0.0', description: 'Container management', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['docker', 'devops'], mcp: { command: 'npx', args: ['-y', 'mcp-server-docker'] }, source: 'official', verified: true, downloads: 2900, rating: 4.5 },
  { id: 'ocean.eslint-plugin', name: 'ESLint Runner', version: '1.0.0', description: 'Lint workspace files', author: 'Ocean.studio', platforms: ['electron', 'web'], type: 'tool', tags: ['lint', 'quality'], tools: [{ name: 'run_eslint', description: 'Run ESLint' }], electron: { entry: 'lint' }, source: 'official', verified: true, downloads: 2200, rating: 4.4 },
  { id: 'ocean.prettier-plugin', name: 'Prettier Formatter', version: '1.0.0', description: 'Format code files', author: 'Ocean.studio', platforms: ['electron', 'web'], type: 'tool', tags: ['format'], tools: [{ name: 'format_file', description: 'Format with Prettier' }], source: 'official', verified: true, downloads: 2100, rating: 4.4 },
  { id: 'ocean.npm-plugin', name: 'NPM Scripts', version: '1.0.0', description: 'Run npm scripts in workspace', author: 'Ocean.studio', platforms: ['electron'], type: 'tool', tags: ['npm', 'scripts'], tools: [{ name: 'npm_run', description: 'Run npm script' }], source: 'official', verified: true, downloads: 4400, rating: 4.7 },
  { id: 'ocean.env-manager', name: 'Env Manager', version: '1.0.0', description: 'Manage .env files securely', author: 'Ocean.studio', platforms: ['electron', 'web'], type: 'tool', tags: ['env', 'config'], tools: [{ name: 'read_env', description: 'Read env vars' }], source: 'official', verified: true, downloads: 1800, rating: 4.3 },
  { id: 'ocean.markdown-preview', name: 'Markdown Preview', version: '1.0.0', description: 'Live markdown rendering', author: 'Ocean.studio', platforms: ['electron', 'web', 'mobile'], type: 'ui', tags: ['markdown', 'preview'], source: 'official', verified: true, downloads: 2700, rating: 4.5 },
  { id: 'ocean.json-schema', name: 'JSON Schema Validator', version: '1.0.0', description: 'Validate JSON against schemas', author: 'Ocean.studio', platforms: ['electron', 'web'], type: 'tool', tags: ['json', 'validation'], tools: [{ name: 'validate_json', description: 'Validate JSON' }], source: 'official', verified: true, downloads: 1600, rating: 4.3 },
  { id: 'ocean.http-client', name: 'HTTP Client', version: '1.0.0', description: 'Test API endpoints', author: 'Ocean.studio', platforms: ['electron', 'web', 'mobile'], type: 'tool', tags: ['http', 'api'], tools: [{ name: 'http_request', description: 'Send HTTP request' }], source: 'official', verified: true, downloads: 2300, rating: 4.4 },
  { id: 'ocean.screenshot', name: 'Screenshot Tool', version: '1.0.0', description: 'Capture preview screenshots', author: 'Ocean.studio', platforms: ['electron'], type: 'tool', tags: ['screenshot'], tools: [{ name: 'capture', description: 'Take screenshot' }], source: 'official', verified: true, downloads: 1500, rating: 4.2 },
  { id: 'ocean.tailwind-helper', name: 'Tailwind Helper', version: '1.0.0', description: 'Tailwind class suggestions', author: 'Ocean.studio', platforms: ['electron', 'web'], type: 'tool', tags: ['css', 'tailwind'], tools: [{ name: 'suggest_classes', description: 'Suggest Tailwind classes' }], source: 'official', verified: true, downloads: 1900, rating: 4.4 },
  // ── Web scraping plugins (default choices) ──
  { id: 'ocean.scrape-firecrawl', name: 'Firecrawl Scraper', version: '1.0.0', description: 'Cloud web scraping — default for all platforms', author: 'Ocean.studio', platforms: ['electron', 'web', 'mobile'], type: 'mcp', tags: ['scrape', 'web', 'firecrawl'], mcp: { transport: 'sse', url: 'https://mcp.firecrawl.dev/sse' }, configSchema: { FIRECRAWL_API_KEY: { type: 'string', description: 'Firecrawl API key' } }, source: 'official', verified: true, downloads: 6100, rating: 4.8 },
  { id: 'ocean.scrape-puppeteer', name: 'Puppeteer Scraper', version: '1.0.0', description: 'Headless Chrome scraping — desktop only', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['scrape', 'browser', 'puppeteer'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] }, source: 'official', verified: true, downloads: 4300, rating: 4.7 },
  { id: 'ocean.scrape-playwright', name: 'Playwright Scraper', version: '1.0.0', description: 'Cross-browser scraping — desktop only', author: 'Ocean.studio', platforms: ['electron'], type: 'mcp', tags: ['scrape', 'browser', 'playwright'], mcp: { command: 'npx', args: ['-y', '@playwright/mcp'] }, source: 'official', verified: true, downloads: 3900, rating: 4.7 },
  { id: 'ocean.scrape-fetch', name: 'HTTP Fetch Scraper', version: '1.0.0', description: 'Lightweight HTTP fetch — works everywhere', author: 'Ocean.studio', platforms: ['electron', 'web', 'mobile'], type: 'mcp', tags: ['scrape', 'fetch', 'web'], mcp: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-fetch'] }, source: 'official', verified: true, downloads: 5200, rating: 4.6 },
  { id: 'ocean.scrape-custom', name: 'Custom Scraper', version: '1.0.0', description: 'Configure your own scraping endpoint or model', author: 'Ocean.studio', platforms: ['electron', 'web', 'mobile'], type: 'tool', tags: ['scrape', 'custom'], configSchema: { endpoint: { type: 'string', description: 'Scraping API endpoint' }, apiKey: { type: 'string', description: 'API key' } }, tools: [{ name: 'scrape_url', description: 'Scrape a URL via custom endpoint' }], source: 'official', verified: true, downloads: 1800, rating: 4.4 },
];

export function getOfficialPlugins(platform: 'electron' | 'web' | 'mobile'): OceanPluginManifest[] {
  const key = platform === 'electron' ? 'electron' : platform === 'mobile' ? 'mobile' : 'web';
  return OFFICIAL_PLUGINS.filter((p) => p.platforms.includes(key));
}
