import type { McpConnectorDefinition } from './types';

const NPX = 'npx';
const Y = '-y';

/** 30+ production MCP connectors — stdio (local/desktop), SSE/HTTP (cloud/web) */
export const MCP_CATALOG: McpConnectorDefinition[] = [
  // ── Local stdio (desktop) ──────────────────────────────────────────
  {
    id: 'mcp.filesystem',
    name: 'Filesystem',
    description: 'Read, write, and search files in your workspace',
    category: 'Core',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-filesystem'],
    verified: true,
    docsUrl: 'https://github.com/modelcontextprotocol/servers',
  },
  {
    id: 'mcp.github',
    name: 'GitHub',
    description: 'Repos, issues, PRs, and code search',
    category: 'Dev',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-github'],
    envFields: [{ key: 'GITHUB_PERSONAL_ACCESS_TOKEN', label: 'GitHub PAT', secret: true, required: true }],
    verified: true,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
  },
  {
    id: 'mcp.gitlab',
    name: 'GitLab',
    description: 'GitLab projects, merge requests, and CI',
    category: 'Dev',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-gitlab'],
    envFields: [{ key: 'GITLAB_PERSONAL_ACCESS_TOKEN', label: 'GitLab Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.brave-search',
    name: 'Brave Search',
    description: 'Web search for agent research',
    category: 'Search',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-brave-search'],
    envFields: [{ key: 'BRAVE_API_KEY', label: 'Brave API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.postgres',
    name: 'PostgreSQL',
    description: 'Query and manage PostgreSQL databases',
    category: 'Database',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-postgres'],
    envFields: [{ key: 'POSTGRES_CONNECTION_STRING', label: 'Connection String', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.sqlite',
    name: 'SQLite',
    description: 'Local SQLite database queries',
    category: 'Database',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-sqlite'],
    envFields: [{ key: 'SQLITE_DB_PATH', label: 'Database Path', required: true }],
    verified: true,
  },
  {
    id: 'mcp.redis',
    name: 'Redis',
    description: 'Redis key-value operations',
    category: 'Database',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-redis'],
    envFields: [{ key: 'REDIS_URL', label: 'Redis URL', placeholder: 'redis://localhost:6379' }],
    verified: true,
  },
  {
    id: 'mcp.puppeteer',
    name: 'Puppeteer',
    description: 'Browser automation and scraping',
    category: 'Automation',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-puppeteer'],
    verified: true,
  },
  {
    id: 'mcp.memory',
    name: 'Memory',
    description: 'Persistent knowledge graph for the agent',
    category: 'Core',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-memory'],
    verified: true,
  },
  {
    id: 'mcp.sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Structured reasoning chains for complex tasks',
    category: 'AI',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-sequential-thinking'],
    verified: true,
  },
  {
    id: 'mcp.fetch',
    name: 'Fetch',
    description: 'HTTP fetch and web content retrieval',
    category: 'Web',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-fetch'],
    verified: true,
  },
  {
    id: 'mcp.google-maps',
    name: 'Google Maps',
    description: 'Geocoding, places, and directions',
    category: 'Maps',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-google-maps'],
    envFields: [{ key: 'GOOGLE_MAPS_API_KEY', label: 'Google Maps API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.slack',
    name: 'Slack',
    description: 'Send messages and read Slack channels',
    category: 'Communication',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-slack'],
    envFields: [{ key: 'SLACK_BOT_TOKEN', label: 'Slack Bot Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.sentry',
    name: 'Sentry',
    description: 'Error tracking and issue management',
    category: 'DevOps',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@modelcontextprotocol/server-sentry'],
    envFields: [{ key: 'SENTRY_AUTH_TOKEN', label: 'Sentry Auth Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.docker',
    name: 'Docker',
    description: 'Manage Docker containers and images',
    category: 'DevOps',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, 'mcp-server-docker'],
    verified: true,
  },
  {
    id: 'mcp.kubernetes',
    name: 'Kubernetes',
    description: 'kubectl operations via MCP',
    category: 'DevOps',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, 'mcp-server-kubernetes'],
    verified: true,
  },
  {
    id: 'mcp.e2b',
    name: 'E2B Code Interpreter',
    description: 'Sandboxed code execution environments',
    category: 'AI',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@e2b/mcp-server'],
    envFields: [{ key: 'E2B_API_KEY', label: 'E2B API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.playwright',
    name: 'Playwright',
    description: 'Cross-browser testing and automation',
    category: 'Automation',
    transport: 'stdio',
    hosting: 'local',
    platforms: ['electron'],
    command: NPX, args: [Y, '@playwright/mcp'],
    verified: true,
  },

  // ── Cloud SSE / HTTP (web + desktop + mobile) ──────────────────────
  {
    id: 'mcp.firecrawl',
    name: 'Firecrawl',
    description: 'Web scraping and crawling via cloud SSE',
    category: 'Web',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.firecrawl.dev/sse',
    envFields: [{ key: 'FIRECRAWL_API_KEY', label: 'Firecrawl API Key', secret: true, required: true }],
    auth: { type: 'api_key', tokenHeader: 'Authorization' },
    verified: true,
    docsUrl: 'https://docs.firecrawl.dev/mcp',
  },
  {
    id: 'mcp.deepwiki',
    name: 'DeepWiki',
    description: 'GitHub repo documentation via SSE',
    category: 'Dev',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.deepwiki.com/sse',
    verified: true,
  },
  {
    id: 'mcp.cloudflare-docs',
    name: 'Cloudflare Docs',
    description: 'Cloudflare documentation search',
    category: 'Cloud',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://docs.mcp.cloudflare.com/sse',
    verified: true,
    docsUrl: 'https://developers.cloudflare.com/agents/model-context-protocol/',
  },
  {
    id: 'mcp.huggingface',
    name: 'Hugging Face',
    description: 'Models, datasets, and inference API',
    category: 'AI',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://huggingface.co/mcp',
    envFields: [{ key: 'HF_TOKEN', label: 'Hugging Face Token', secret: true }],
    verified: true,
  },
  {
    id: 'mcp.supabase',
    name: 'Supabase',
    description: 'Database, auth, and storage via Supabase MCP',
    category: 'Database',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.supabase.com/sse',
    envFields: [{ key: 'SUPABASE_ACCESS_TOKEN', label: 'Supabase Access Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.linear',
    name: 'Linear',
    description: 'Issue tracking and project management',
    category: 'Productivity',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.linear.app/sse',
    envFields: [{ key: 'LINEAR_API_KEY', label: 'Linear API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.notion',
    name: 'Notion',
    description: 'Notion pages and databases',
    category: 'Productivity',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web'],
    url: 'https://mcp.notion.com/sse',
    auth: {
      type: 'oauth',
      oauthAuthorizeUrl: 'https://api.notion.com/v1/oauth/authorize',
      oauthTokenUrl: 'https://api.notion.com/v1/oauth/token',
      oauthScopes: [],
    },
    verified: true,
  },
  {
    id: 'mcp.stripe',
    name: 'Stripe',
    description: 'Payments, customers, and subscriptions',
    category: 'Finance',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.stripe.com/sse',
    envFields: [{ key: 'STRIPE_SECRET_KEY', label: 'Stripe Secret Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.perplexity',
    name: 'Perplexity',
    description: 'AI-powered web search and answers',
    category: 'Search',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.perplexity.ai/sse',
    envFields: [{ key: 'PERPLEXITY_API_KEY', label: 'Perplexity API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.anthropic',
    name: 'Anthropic',
    description: 'Claude API tools via MCP bridge',
    category: 'AI',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.anthropic.com/sse',
    envFields: [{ key: 'ANTHROPIC_API_KEY', label: 'Anthropic API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.openai',
    name: 'OpenAI',
    description: 'GPT models and tools via MCP',
    category: 'AI',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.openai.com/sse',
    envFields: [{ key: 'OPENAI_API_KEY', label: 'OpenAI API Key', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.asana',
    name: 'Asana',
    description: 'Tasks and project management',
    category: 'Productivity',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.asana.com/sse',
    envFields: [{ key: 'ASANA_ACCESS_TOKEN', label: 'Asana Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.twilio',
    name: 'Twilio',
    description: 'SMS, voice, and messaging',
    category: 'Communication',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web'],
    url: 'https://mcp.twilio.com/sse',
    envFields: [
      { key: 'TWILIO_ACCOUNT_SID', label: 'Account SID', required: true },
      { key: 'TWILIO_AUTH_TOKEN', label: 'Auth Token', secret: true, required: true },
    ],
    verified: true,
  },
  {
    id: 'mcp.azure',
    name: 'Azure',
    description: 'Azure cloud services and resources',
    category: 'Cloud',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web'],
    url: 'https://mcp.azure.com/sse',
    auth: { type: 'oauth', oauthAuthorizeUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', oauthTokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token', oauthScopes: ['https://management.azure.com/.default'] },
    verified: true,
  },
  {
    id: 'mcp.aws',
    name: 'AWS Knowledge Base',
    description: 'AWS documentation and KB search',
    category: 'Cloud',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.aws.amazon.com/sse',
    envFields: [{ key: 'AWS_ACCESS_KEY_ID', label: 'AWS Access Key' }, { key: 'AWS_SECRET_ACCESS_KEY', label: 'AWS Secret', secret: true }],
    verified: true,
  },
  {
    id: 'mcp.vercel',
    name: 'Vercel',
    description: 'Deployments and project management',
    category: 'DevOps',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.vercel.com/sse',
    envFields: [{ key: 'VERCEL_TOKEN', label: 'Vercel Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.netlify',
    name: 'Netlify',
    description: 'Sites, deploys, and forms',
    category: 'DevOps',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.netlify.com/sse',
    envFields: [{ key: 'NETLIFY_AUTH_TOKEN', label: 'Netlify Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.sentry-cloud',
    name: 'Sentry Cloud',
    description: 'Sentry issues via hosted SSE',
    category: 'DevOps',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.sentry.io/sse',
    envFields: [{ key: 'SENTRY_AUTH_TOKEN', label: 'Sentry Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.mongodb',
    name: 'MongoDB',
    description: 'MongoDB Atlas database operations',
    category: 'Database',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.mongodb.com/sse',
    envFields: [{ key: 'MONGODB_URI', label: 'MongoDB URI', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.cloudflare-workers',
    name: 'Cloudflare Workers',
    description: 'Deploy and manage Workers',
    category: 'Cloud',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://workers.mcp.cloudflare.com/sse',
    envFields: [{ key: 'CLOUDFLARE_API_TOKEN', label: 'Cloudflare API Token', secret: true, required: true }],
    verified: true,
  },
  {
    id: 'mcp.github-cloud',
    name: 'GitHub Cloud MCP',
    description: 'GitHub via hosted SSE (no local npx)',
    category: 'Dev',
    transport: 'sse',
    hosting: 'cloud',
    platforms: ['electron', 'web', 'mobile'],
    url: 'https://mcp.github.com/sse',
    auth: {
      type: 'oauth',
      oauthAuthorizeUrl: 'https://github.com/login/oauth/authorize',
      oauthTokenUrl: 'https://github.com/login/oauth/access_token',
      oauthScopes: ['repo', 'read:user'],
    },
    verified: true,
  },
];

export function getCloudMcpMarketplace(platform: 'electron' | 'web' | 'mobile'): McpConnectorDefinition[] {
  return MCP_CATALOG.filter((c) => c.hosting === 'cloud' && c.platforms.includes(platform));
}

export function getCatalogForPlatform(platform: 'electron' | 'web' | 'mobile'): McpConnectorDefinition[] {
  return MCP_CATALOG.filter((c) => c.platforms.includes(platform));
}

export function getConnectorById(id: string): McpConnectorDefinition | undefined {
  return MCP_CATALOG.find((c) => c.id === id);
}
