package studio.ocean.app.terminal;

import android.content.*;import android.net.Uri;import android.os.Bundle;import android.widget.*;import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.core.content.FileProvider;import java.io.*;

/** Temporary device diagnostic controls and complete SAF/FileProvider exports. */
public final class OceanTerminalDiagnosticsActivity extends AppCompatActivity {
 private boolean zipExport;private TextView report;private final ActivityResultLauncher<Intent> createDocument=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),result->{if(result.getResultCode()!=RESULT_OK||result.getData()==null)return;Uri uri=result.getData().getData();if(uri==null)return;try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(zipExport)TerminalDiagnosticBundle.writeZip(this,out);else TerminalDiagnosticBundle.writeText(this,out);Toast.makeText(this,"Diagnostic downloaded",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Download failed: "+e,Toast.LENGTH_LONG).show();}});
 @Override protected void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);TextView title=new TextView(this);title.setText("Ocean Terminal Diagnostics");title.setTextSize(20);root.addView(title);root.addView(button("DOWNLOAD DIAGNOSTIC",v->download(false)));root.addView(button("DOWNLOAD DIAGNOSTIC ZIP",v->download(true)));root.addView(button("SHARE DIAGNOSTIC ZIP",v->share()));root.addView(button("PTY TEST A — Android system shell",v->test("A")));root.addView(button("PTY TEST B — Ocean Bash interactive",v->test("B")));root.addView(button("PTY TEST C — Ocean Bash scripted OCEAN_PTY_OK",v->test("C")));report=new TextView(this);report.setTypeface(android.graphics.Typeface.MONOSPACE);report.setTextIsSelectable(true);report.setText(TerminalDiagnosticBundle.summary(this));ScrollView scroll=new ScrollView(this);scroll.addView(report);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private Button button(String s,android.view.View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);return b;}
 private void download(boolean zip){zipExport=zip;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType(zip?"application/zip":"text/plain").putExtra(Intent.EXTRA_TITLE,TerminalDiagnosticBundle.fileName(zip?"zip":"txt")).addCategory(Intent.CATEGORY_OPENABLE);createDocument.launch(i);}
 private void share(){try{File f=TerminalDiagnosticBundle.shareZip(this);Uri uri=FileProvider.getUriForFile(this,getPackageName()+".diagnostics",f);startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("application/zip").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION),"Share Ocean diagnostic"));}catch(Exception e){Toast.makeText(this,"Share failed: "+e,Toast.LENGTH_LONG).show();}}
 private void test(String test){startActivity(new Intent(this,OceanTerminalActivity.class).putExtra("diagnostic_test",test));}

}
